# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 23 Nov 2022 09:58:04 +0000
*	@ALL	0
*	@user	16
asanchezcastillo	@ALL	0
asanchezcastillo	asanchezcastillo	2
ferfuentguerr	@ALL	1
ferfuentguerr	ferfuentguerr	2
ugrlab	@ALL	0
wiki:*	@ALL	1
