<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: ugrlab
 * Date: Wed, 23 Nov 2022 11:07:15 +0100
 */

$conf['title'] = 'NeutrinoUGR';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
