<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Wed, 23 Nov 2022 09:58:04 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
