# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 23 Nov 2022 09:58:04 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

ugrlab:$2y$10$MYSm9RNBcQCNV4xZcDBbBOsGjDtcAcIs7YeKq6RPxVkNfifFivuSC:ugrlab:ferfuentguerr@ugr.es:admin,user
dgarciag:$2y$10$32CLcXf5NfWaBbj7VnOIpu6BPFO2WvdcW4WvIiGa7utgu5yiUUNry:Diego Garcia Gamez:dgarciag@ugr.es:user
pslucas:$2y$10$nS0n7uwhhRiWHummWw5ID.8U1HyIMQfxBUw.UlaOT0w8k4zvokIcK:Patricia Sanchez Lucas:patriciasl@ugr.es:user
bzamorano:$2y$10$pAR6YUz5Q1VAYYsJh1FA0OY7JQwxpjgrrbfy9xefpoX6EEM1ou1l2:Bruno Zamorano:bzamorano@ugr.es:user
fjnicolas:$2y$10$THINo1k027nzMKYVmCKM2Omu8f.FKLdXO6QC4VKaIIBeda/wb7Muu:Francisco Javier Nicolas:fjnicolas@ugr.es:user
asanchezcastillo:$2y$10$yvI2aj0Qh4o6oJ9vVy9JTek.CMk3BIXJ4kevTmMvRf4kgwqyhrMFu:Alejandro Sánchez Castillo:asanchezcastillo@ugr.es:user
lpelegrina:$2y$10$aFomdr8uN3j4ZhAerfs7mehpLr7tEPd/NQCEmZduiZKJs3Zj.VtnS:Luis Pelegrina:lpelegrina@correo.ugr.es:user
ejgarcia:$2y$10$zPFmWDx3o1R96DlAzSXxQuYmk9toK3Ar7pvMax884Vhsq8fUkkbVW:Elena Jimenez Garcia:ejgarcia@ugr.es:user
abueno:$2y$10$uo1tHM6XYJ2xQ1JN4T2aPeMw5mm.RpY32E0JACFUYLjsIsUPH.eym:Antonio Bueno:abueno@ugr.es:user
ferfuentguerr:$2y$10$RHW4dZvCEzpGUtTMqKMnRuM98mUxHziIZ9fTGvWaJe99/AmnKIax6:Fernando Fuentes-Guerra:ferfuentguerr@ugr.es:user
aliciavr:$2y$10$8bvHiILuQtvfxKaSlVV0JeE3F3LJMEb1z.y1LzS1RU6cS2ORVcdrS:Alicia Vázquez Ramos:aliciavr@ugr.es:user
